#!/usr/bin/env bash

set -euo pipefail

cd -- "$(dirname "$0")/.."

PATH="$PWD/target/installdir/bin:$PATH"
controller_bin="$(cargo build --message-format=json --bin bar-panel-controller --features=__bin "$@" | jq -r -c 'select(.target.name == "bar-panel-controller") | .executable')"
example_bin="$(cargo build --message-format=json -p example-bar "$@" | jq -r -c 'select(.target.name == "example-bar") | .executable')"
exec "${controller_bin:?}" "${example_bin:?}"
