#!/usr/bin/env bash

if [[ -v NO_DEBUG ]]; then
    profile=()
else
    profile="--debug"
fi

cd -- "$(dirname "$0")/.."

PATH="$PWD/target/installdir/bin:$PATH"
cargo install $profile --offline --path . --root target/installdir --features=__bin "$@" || exit 1
cargo install $profile --offline --path ./example-bar --root target/installdir "$@" || exit 1
bar-panel-controller example-bar
